Testing build script.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -11,12 +11,22 @@ after_success:
   - cd $TRAVIS_BUILD_DIR
   - echo "Building java services"
   - mvn -DskipTests package
+  - MVN_EXIT=$(echo $?)
+  - if [[ "$MVN_EXIT" > 0 ]] ; then
+      echo "Compilation failed with exit code $MVN_EXIT";
+      exit 1
+    fi;
 
   - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
   - for module in ${MODULES}; do
       export REPO=${GROUP}/${module};
       echo "Building ${REPO}:$COMMIT";
       docker build -t ${REPO}:$COMMIT ./${module};
+      DOCKER_EXIT=$(echo $?);
+      if [[ "$DOCKER_EXIT" > 0 ]] ; then
+        echo "Docker build failed with exit code $DOCKER_EXIT";
+        exit 1;
+      fi;
       echo "Pushing $REPO:$COMMIT";
       docker push $REPO:$COMMIT;
       if [ "$TRAVIS_BRANCH" == "master" ]; then docker tag $REPO:$COMMIT $REPO:snapshot; echo "Pushing $REPO:snapshot"; docker push $REPO:snapshot; fi;
