Add while loop around docker push to prevent docker hub 500's.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -30,13 +30,15 @@ after_success:
         echo "Docker build failed with exit code $DOCKER_EXIT";
         exit 1;
       fi;
-      echo "Pushing $REPO:$TRAVIS_COMMIT";
-      docker push $REPO:$TRAVIS_COMMIT;
-      DOCKER_PUSH=$(echo $?);
-      if [[ "$DOCKER_PUSH" > 0 ]] ; then
-        echo "Docker push failed with exit code $DOCKER_PUSH";
-        exit 1;
-      fi;
+      DOCKER_PUSH=1
+      while [ $DOCKER_PUSH > 0 ] ; do
+        echo "Pushing $REPO:$TRAVIS_COMMIT";
+        docker push $REPO:$TRAVIS_COMMIT;
+        DOCKER_PUSH=$(echo $?);
+        if [[ "$DOCKER_PUSH" > 0 ]] ; then
+          echo "Docker push failed with exit code $DOCKER_PUSH";
+        fi;
+      done;
       if [ "$TRAVIS_BRANCH" == "master" ]; then docker tag $REPO:$TRAVIS_COMMIT $REPO:snapshot; echo "Pushing $REPO:snapshot"; docker push $REPO:snapshot; fi;
       if [ ! -z "$TRAVIS_TAG" ]; then docker tag $REPO:$TRAVIS_COMMIT $REPO:$TRAVIS_TAG; docker push $REPO:$TRAVIS_TAG; docker tag $REPO:$TRAVIS_COMMIT $REPO:latest; docker push $REPO:latest; fi;
     done;
