Remove testing; tidy up travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -7,34 +7,31 @@ jdk:
 script:
 - "echo skip"
 after_success:
-  - export MODULES="openapi"
   - export GROUP=weaveworksdemos
   - if [ -z "$DOCKER_PASS" ] ; then
       echo "This is a build triggered by an external PR. Skipping docker push.";
       exit 0;
     fi;
   - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
-  - for module in ${MODULES}; do
-      export REPO=${GROUP}/$(basename ${module});
-      echo "Building ${REPO}:$TRAVIS_COMMIT";
-      docker build -t ${REPO}:$TRAVIS_COMMIT ./${module};
-      DOCKER_EXIT=$(echo $?);
-      if [[ "$DOCKER_EXIT" > 0 ]] ; then
-        echo "Docker build failed with exit code $DOCKER_EXIT";
-        exit 1;
+  - export REPO=${GROUP}/$(basename openapi); # build openapi testing image
+    echo "Building ${REPO}:$TRAVIS_COMMIT";
+    docker build -t ${REPO}:$TRAVIS_COMMIT ./openapi;
+    DOCKER_EXIT=$(echo $?);
+    if [[ "$DOCKER_EXIT" > 0 ]] ; then
+      echo "Docker build failed with exit code $DOCKER_EXIT";
+      exit 1;
+    fi;
+    DOCKER_PUSH=1;
+    while [ $DOCKER_PUSH -gt 0 ] ; do
+      echo "Pushing $REPO:$TRAVIS_COMMIT";
+      docker push $REPO:$TRAVIS_COMMIT;
+      DOCKER_PUSH=$(echo $?);
+      if [[ "$DOCKER_PUSH" -gt 0 ]] ; then
+        echo "Docker push failed with exit code $DOCKER_PUSH";
       fi;
-      DOCKER_PUSH=1;
-      while [ $DOCKER_PUSH -gt 0 ] ; do
-        echo "Pushing $REPO:$TRAVIS_COMMIT";
-        docker push $REPO:$TRAVIS_COMMIT;
-        DOCKER_PUSH=$(echo $?);
-        if [[ "$DOCKER_PUSH" -gt 0 ]] ; then
-          echo "Docker push failed with exit code $DOCKER_PUSH";
-        fi;
-      done;
-      if [ "$TRAVIS_BRANCH" == "master" ]; then docker tag $REPO:$TRAVIS_COMMIT $REPO:snapshot; echo "Pushing $REPO:snapshot"; docker push $REPO:snapshot; fi;
-      if [ ! -z "$TRAVIS_TAG" ]; then docker tag $REPO:$TRAVIS_COMMIT $REPO:$TRAVIS_TAG; docker push $REPO:$TRAVIS_TAG; docker tag $REPO:$TRAVIS_COMMIT $REPO:latest; docker push $REPO:latest; fi;
     done;
+    if [ "$TRAVIS_BRANCH" == "master" ]; then docker tag $REPO:$TRAVIS_COMMIT $REPO:snapshot; echo "Pushing $REPO:snapshot"; docker push $REPO:snapshot; fi;
+    if [ ! -z "$TRAVIS_TAG" ]; then docker tag $REPO:$TRAVIS_COMMIT $REPO:$TRAVIS_TAG; docker push $REPO:$TRAVIS_TAG; docker tag $REPO:$TRAVIS_COMMIT $REPO:latest; docker push $REPO:latest; fi;
 
 notifications:
   slack:
